In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()

In [5]:
df = pd.DataFrame(data.data,columns=data.feature_names)
df['Price'] = data.target

In [6]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [9]:
df.shape

(20640, 9)

In [12]:
df = df.sample(frac = 0.20)

In [13]:
df.shape

(4128, 9)

In [14]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
20309,4.8125,22.0,4.811940,0.997015,1431.0,4.271642,34.17,-119.15,1.944
16717,3.3125,19.0,5.126722,1.002755,1040.0,2.865014,35.50,-120.66,1.639
14898,2.3929,30.0,3.000000,1.083333,220.0,4.583333,32.59,-117.08,1.344
20269,2.6964,21.0,4.660377,1.198113,489.0,4.613208,34.20,-119.18,1.708
15026,2.6678,34.0,5.076220,1.102134,1592.0,2.426829,32.77,-117.01,1.642
...,...,...,...,...,...,...,...,...,...
8813,6.2870,34.0,6.268097,1.053619,1031.0,2.764075,33.75,-118.31,3.964
16524,3.5625,24.0,5.424920,1.099042,927.0,2.961661,37.80,-121.20,1.308
7730,4.1786,36.0,4.776699,0.888350,615.0,2.985437,33.92,-118.13,2.015
17491,2.1417,31.0,2.651163,1.149502,699.0,2.322259,34.43,-119.83,2.050
5586,5.3106,27.0,5.375723,0.988439,1498.0,2.886320,33.80,-118.30,2.683

In [30]:
df = pd.DataFrame(data.data,columns = data.feature_names)

In [31]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [32]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [33]:
X = df
y = df.target

AttributeError: 'DataFrame' object has no attribute 'target'

In [8]:
# Independent 
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

In [15]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [16]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split ( X,y,test_size=0.3, random_state=30)

In [26]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(criterion = 'entropy')

In [27]:
regressor

DecisionTreeRegressor(criterion='entropy')

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 20)